# Generated by Django 5.0.6 on 2024-07-04 12:25

import bazis.contrib.permit.schemas
import model_clone.mixin
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildEntity',
            fields=[
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time')),
                ('dt_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=255)),
                ('child_description', models.TextField(blank=True, null=True)),
                ('child_is_active', models.BooleanField(default=True)),
                ('child_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('child_dt_approved', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Child entity',
                'verbose_name_plural': 'Child entities',
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DependentEntity',
            fields=[
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time')),
                ('dt_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependent_name', models.CharField(max_length=255)),
                ('dependent_description', models.TextField(blank=True, null=True)),
                ('dependent_is_active', models.BooleanField(default=True)),
                ('dependent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dependent_dt_approved', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dependent entity',
                'verbose_name_plural': 'Dependent entities',
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExtendedEntity',
            fields=[
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time')),
                ('dt_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extended_name', models.CharField(max_length=255)),
                ('extended_description', models.TextField(blank=True, null=True)),
                ('extended_is_active', models.BooleanField(default=True)),
                ('extended_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extended_dt_approved', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Extended entity',
                'verbose_name_plural': 'Extended entities',
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ParentEntity',
            fields=[
                ('dt_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time')),
                ('dt_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dt_approved', models.DateTimeField(blank=True, null=True)),
                ('status_dt', models.DateTimeField(auto_now_add=True, verbose_name='Status timestamp')),
            ],
            options={
                'verbose_name': 'Parent entity',
                'verbose_name_plural': 'Parent entities',
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model, bazis.contrib.permit.schemas.PermitStructMixin),
        ),
        migrations.CreateModel(
            name='ParentEntityStatusyTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Status timestamp')),
                ('extra', models.JSONField(default=dict, verbose_name='Transit extra data')),
            ],
            options={
                'verbose_name': 'Parent entity. Transit fact',
                'verbose_name_plural': 'Parent entities. Transit facts',
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
