# Generated by Django 5.0.6 on 2024-07-04 12:25

import bazis.contrib.statusy.models_abstract
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
        ('statusy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='childentity',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childentity',
            name='author_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childentity',
            name='author_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependententity',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependententity',
            name='author_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependententity',
            name='author_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extendedentity',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extendedentity',
            name='author_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extendedentity',
            name='author_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parententity',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parententity',
            name='author_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parententity',
            name='child_entities',
            field=models.ManyToManyField(blank=True, related_name='parent_entities', to='entity.childentity'),
        ),
        migrations.AddField(
            model_name='parententity',
            name='status',
            field=models.ForeignKey(default=bazis.contrib.statusy.models_abstract.status_default, on_delete=django.db.models.deletion.CASCADE, to='statusy.status', verbose_name='Current status'),
        ),
        migrations.AddField(
            model_name='parententity',
            name='status_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_author_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extendedentity',
            name='parent_entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_entity', to='entity.parententity'),
        ),
        migrations.AddField(
            model_name='dependententity',
            name='parent_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_entities', to='entity.parententity'),
        ),
        migrations.AddField(
            model_name='parententitystatusytransit',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_author_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parententitystatusytransit',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='statusy.status'),
        ),
        migrations.AddField(
            model_name='parententitystatusytransit',
            name='statusy_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusy_transits', to='entity.parententity'),
        ),
        migrations.AddField(
            model_name='parententitystatusytransit',
            name='transit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='statusy.transit'),
        ),
    ]
