# Generated by Django 5.0.1 on 2025-12-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_parententity_autogen_author_selectors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parententity',
            name='autogen_author_selectors',
        ),
        migrations.RemoveField(
            model_name='parententity',
            name='autogen_author_updated_selectors',
        ),
        migrations.RemoveField(
            model_name='parententity',
            name='autogen_status_author_selectors',
        ),
    ]
