# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.0.14 on 2025-09-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='hint_action',
            field=models.TextField(blank=True, null=True, verbose_name='Note action'),
        ),
        migrations.AddField(
            model_name='transit',
            name='hint_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note title'),
        ),
    ]
