# Generated by Django 5.0.14 on 2025-09-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='hint_action',
            field=models.TextField(blank=True, null=True, verbose_name='Note action'),
        ),
        migrations.AddField(
            model_name='transit',
            name='hint_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note title'),
        ),
    ]
