# Generated by Django 5.0.1 on 2025-12-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusy', '0002_transit_hint_action_transit_hint_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='transit',
            old_name='hint_title',
            new_name='hint_title_en',
        ),
        migrations.RenameField(
            model_name='transit',
            old_name='name',
            new_name='name_en',
        ),
    ]
