# Generated by Django 5.0.1 on 2025-12-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusy', '0003_rename_name_status_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='transit',
            name='hint_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note title'),
        ),
        migrations.AddField(
            model_name='transit',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
    ]
