# Generated by Django 5.0.1 on 2025-12-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusy', '0004_status_name_ru_transit_hint_title_ru_transit_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
    ]
