# Generated by Django 6.1.1 on 2026-10-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statusy", "0005_alter_status_name_en_alter_status_name_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transit",
            name="transits_related",
            field=models.ManyToManyField(
                blank=True,
                through="statusy.TransitRelation",
                through_fields=("transit_parent", "transit_child"),
                to="statusy.transit",
                verbose_name="Related transits",
            ),
        ),
    ]
