# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 6.1.1 on 2026-10-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statusy", "0005_alter_status_name_en_alter_status_name_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transit",
            name="transits_related",
            field=models.ManyToManyField(
                blank=True,
                through="statusy.TransitRelation",
                through_fields=("transit_parent", "transit_child"),
                to="statusy.transit",
                verbose_name="Related transits",
            ),
        ),
    ]
